import { CS_NETWORK_AND_INTERNET_BEGINNER_TOPICS } from './beginner';
import { CS_NETWORK_AND_INTERNET_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_NETWORK_AND_INTERNET_TOPICS = [
  ...CS_NETWORK_AND_INTERNET_BEGINNER_TOPICS,
  ...CS_NETWORK_AND_INTERNET_INTERMEDIATE_TOPICS
];
