import { Topic } from '../../../types';
import { NETWORK_PERFORMANCE_BEGINNER_TOPICS } from './beginner';
import { NETWORK_PERFORMANCE_INTERMEDIATE_TOPICS } from './intermediate';
import { NETWORK_PERFORMANCE_ADVANCED_TOPICS } from './advanced';

export const NETWORK_PERFORMANCE_TOPICS: Topic[] = [
  ...NETWORK_PERFORMANCE_BEGINNER_TOPICS,
  ...NETWORK_PERFORMANCE_INTERMEDIATE_TOPICS,
  ...NETWORK_PERFORMANCE_ADVANCED_TOPICS
];
