import { CS_ARCHITECTURE_SEPARATION_BEGINNER_TOPICS } from './beginner';
import { CS_ARCHITECTURE_SEPARATION_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_ARCHITECTURE_SEPARATION_TOPICS = [
  ...CS_ARCHITECTURE_SEPARATION_BEGINNER_TOPICS,
  ...CS_ARCHITECTURE_SEPARATION_INTERMEDIATE_TOPICS
];
