import { CS_OPERATING_SYSTEMS_BEGINNER_TOPICS } from './beginner';
import { CS_OPERATING_SYSTEMS_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_OPERATING_SYSTEMS_TOPICS = [
  ...CS_OPERATING_SYSTEMS_BEGINNER_TOPICS,
  ...CS_OPERATING_SYSTEMS_INTERMEDIATE_TOPICS
];
