import { CS_PROGRAMMING_CONCEPT_BEGINNER_TOPICS } from './beginner';
import { CS_PROGRAMMING_CONCEPT_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_PROGRAMMING_CONCEPT_TOPICS = [
  ...CS_PROGRAMMING_CONCEPT_BEGINNER_TOPICS,
  ...CS_PROGRAMMING_CONCEPT_INTERMEDIATE_TOPICS
];
