import { Topic } from '../../../types';
import { RENDERING_STRATEGIES_BEGINNER_TOPICS } from './beginner';
import { RENDERING_STRATEGIES_INTERMEDIATE_TOPICS } from './intermediate';
import { RENDERING_STRATEGIES_ADVANCED_TOPICS } from './advanced';

export const RENDERING_STRATEGIES_TOPICS: Topic[] = [
  ...RENDERING_STRATEGIES_BEGINNER_TOPICS,
  ...RENDERING_STRATEGIES_INTERMEDIATE_TOPICS,
  ...RENDERING_STRATEGIES_ADVANCED_TOPICS
];
