import { Topic } from '../../../types';
import { NETWORK_BROWSER_SECURITY_BEGINNER_TOPICS } from './beginner';
import { NETWORK_BROWSER_SECURITY_INTERMEDIATE_TOPICS } from './intermediate';
import { NETWORK_BROWSER_SECURITY_ADVANCED_TOPICS } from './advanced';

export const NETWORK_BROWSER_SECURITY_TOPICS: Topic[] = [
  ...NETWORK_BROWSER_SECURITY_BEGINNER_TOPICS,
  ...NETWORK_BROWSER_SECURITY_INTERMEDIATE_TOPICS,
  ...NETWORK_BROWSER_SECURITY_ADVANCED_TOPICS
];
