import { Topic } from '../../../types';
import { NETWORK_JAVASCRIPT_NETWORK_BEGINNER_TOPICS } from './beginner';
import { NETWORK_JAVASCRIPT_NETWORK_INTERMEDIATE_TOPICS } from './intermediate';
import { NETWORK_JAVASCRIPT_NETWORK_ADVANCED_TOPICS } from './advanced';

export const NETWORK_JAVASCRIPT_NETWORK_TOPICS: Topic[] = [
  ...NETWORK_JAVASCRIPT_NETWORK_BEGINNER_TOPICS,
  ...NETWORK_JAVASCRIPT_NETWORK_INTERMEDIATE_TOPICS,
  ...NETWORK_JAVASCRIPT_NETWORK_ADVANCED_TOPICS
];
