import { CS_ELECTRONIC_COMPUTERS_BEGINNER_TOPICS } from './beginner';
import { CS_ELECTRONIC_COMPUTERS_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_ELECTRONIC_COMPUTERS_TOPICS = [
  ...CS_ELECTRONIC_COMPUTERS_BEGINNER_TOPICS,
  ...CS_ELECTRONIC_COMPUTERS_INTERMEDIATE_TOPICS
];
