import { Topic } from '../../../types';
import { COMPONENT_ARCHITECTURE_BEGINNER_TOPICS } from './beginner';
import { COMPONENT_ARCHITECTURE_INTERMEDIATE_TOPICS } from './intermediate';
import { COMPONENT_ARCHITECTURE_ADVANCED_TOPICS } from './advanced';

export const COMPONENT_ARCHITECTURE_TOPICS: Topic[] = [
  ...COMPONENT_ARCHITECTURE_BEGINNER_TOPICS,
  ...COMPONENT_ARCHITECTURE_INTERMEDIATE_TOPICS,
  ...COMPONENT_ARCHITECTURE_ADVANCED_TOPICS
];
