import { Topic } from '../../../types';
import { FRONTEND_INFRASTRUCTURE_BEGINNER_TOPICS } from './beginner';
import { FRONTEND_INFRASTRUCTURE_INTERMEDIATE_TOPICS } from './intermediate';

export const FRONTEND_INFRASTRUCTURE_TOPICS: Topic[] = [
  ...FRONTEND_INFRASTRUCTURE_BEGINNER_TOPICS,
  ...FRONTEND_INFRASTRUCTURE_INTERMEDIATE_TOPICS
];
