import { CS_MECHANIZATION_BEGINNER_TOPICS } from './beginner';
import { CS_MECHANIZATION_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_MECHANIZATION_TOPICS = [
  ...CS_MECHANIZATION_BEGINNER_TOPICS,
  ...CS_MECHANIZATION_INTERMEDIATE_TOPICS
];
