import { CS_REPRESENTATION_BEGINNER_TOPICS } from './beginner';
import { CS_REPRESENTATION_INTERMEDIATE_TOPICS } from './intermediate';

export const CS_REPRESENTATION_TOPICS = [
  ...CS_REPRESENTATION_BEGINNER_TOPICS,
  ...CS_REPRESENTATION_INTERMEDIATE_TOPICS
];
