import { Topic } from '../../../types';
import { STYLES_ARCHITECTURE_BEGINNER_TOPICS } from './beginner';
import { STYLES_ARCHITECTURE_INTERMEDIATE_TOPICS } from './intermediate';
import { STYLES_ARCHITECTURE_ADVANCED_TOPICS } from './advanced';

export const STYLES_ARCHITECTURE_TOPICS: Topic[] = [
  ...STYLES_ARCHITECTURE_BEGINNER_TOPICS,
  ...STYLES_ARCHITECTURE_INTERMEDIATE_TOPICS,
  ...STYLES_ARCHITECTURE_ADVANCED_TOPICS
];
